#!/usr/libexec/flua
--
-- SPDX-License-Identifier: BSD-2-Clause
--
-- Copyright (c) 2026 Warner Losh <imp@bsdimp.com>
--

-- Add library root to the package path.
local path = arg[0]:gsub("/[^/]+.lua$", "")
package.path = package.path .. ";" .. path .. "/?.lua;" .. os.getenv('FREEBSD_SYSCALL_DIR') .. "/?.lua"

local FreeBSDSyscall = require("core.freebsd-syscall")
local config = require("config")
local qemu = require("qemu")
local ucl = require("ucl")

-- Convert the type flags set (table with flag=true entries) to a sorted list.
local function flagsToList(typetbl)
	local flags = {}
	for k, _ in pairs(typetbl) do
		table.insert(flags, k)
	end
	table.sort(flags)
	return flags
end

-- Read in the metadata
function get_meta(fn)
	local parser = ucl.parser()
	parser:parse_file(fn)
	local data = parser:get_object()
	-- index table by name
	local meta = {}
	for _,syscall in ipairs(data) do
		meta[syscall.name] = syscall
	end
	return meta
end

-- These types are always 64-bit on 32-bit and 64-bit platforms
function type_always_64(t)
	if t == "int64_t" or t == "uint64_t" or t == "id_t" or t == "off_t" or t == "rlim_t" then
		return true
	end
	return false
end

-- Does this system call have any always 64-bit args?
function syscall_has_always_64(v)
	for _, arg in ipairs(v.args) do
		if type_always_64(arg.type) then
			return true
		end
	end
	return false
end

-- Simple args: no pointers, no struct (though maybe the latter is redundant since
-- all structs are of the form struct foo *
function syscall_simple_args(v)
	for _, arg in ipairs(v.args) do
		t = arg.type
		if t:find("*") then
			return false
		elseif t:find("struct ") or t:find("union ") then
			return false
		end
	end
	return true
end

--
-- System call taking no args. Use the system call interface to avoid type
-- mismatches.
--
function gen_zero_arg(fout, v)
	fout:write(string.format([[
static abi_long do_gen_%s(const os_syscall_args_t *sa) /* %d */
{
    return get_errno(syscall(SYS_%s));
}
]], v:symbol(), v.num, v:symbol()))
end

--
-- Generate the system call when syscall_simple_args is true
--
-- Note: We're always a 64-bit host, so syscall is always correct.
--
function gen_simple_args(fout, v)
	fout:write(string.format([[
static abi_long do_gen_%s(const os_syscall_args_t *sa) /* %d */
{
    ARGS(%s, sa);

    return get_errno(syscall(SYS_%s]], v:symbol(), v.num, v:symbol(), v:symbol()))
	for _, arg in ipairs(v.args) do
		fout:write(", uap->" .. arg.name)
	end
	fout:write("));\n}\n")
end

function generate(tbl, fn, metafn)
	local fout = assert(io.open(fn, "w+"))
	meta = get_meta(metafn)

	local output_head <const> = "/* DO NOT EDIT-- this file is @" .. [[generated by gen_qemu_syscalls.lua */
]]
	fout:write(output_head)
	fout:write([[

#include "qemu/osdep.h"
#include "qemu.h"
#include "os-types.h"
#include "os-sysproto.h"
#include "special-syscall.h"

static abi_long do_nosys(const os_syscall_args_t *arg __unused)
{
    return -ENOSYS;
}
]])

	-- Generate the system call implementation
	for _, v in pairs(tbl.syscalls) do
		if not meta[v:symbol()] then
			meta[v:symbol()] = {}
		end
		if v:bsd_user_impl() and not meta[v:symbol()].custom_impl then
			if #v.args == 0 then
				gen_zero_arg(fout, v)
			elseif syscall_simple_args(v) then
				gen_simple_args(fout, v)
			else
				fout:write(string.format("#define do_gen_%s do_nosys /* %d */\n",
				    v:symbol(), v.num))
			end
		end
	end

	-- Generate the system call table
	fout:write("\nos_syscall_t sysent[] = {\n")
	for _, v in pairs(tbl.syscalls) do
		if v:bsd_user_impl() then
			local prefix
			if meta[v:symbol()].custom_impl then
				prefix = "do_custom_"
			else
				prefix = "do_gen_"
			end
			fout:write(string.format("[%d] = %s%s,\n",
			    v.num, prefix, v:symbol()))
		end
	end
	fout:write("\n};\n")

	-- Now generate the dispatcher, not sure if we want it here or elsewhere
	-- but for now, this is easy enough.
	fout:write([[
/*
 * do_freebsd_syscall() looks up the system call and calls it, or returns
 * an error if it can't find it in the tables.
 */
abi_long do_freebsd_syscall(const os_syscall_args_t *sa)
{
    os_syscall_t fn = do_nosys;
    if ((sa->number >= 0 || sa->number < nitems(sysent)) &&
      sysent[sa->number] != NULL) {
        fn = sysent[sa->number];
    }
    return fn(sa);
}
]])
end


if #arg < 1 or #arg > 2 then
	error("usage: " .. arg[0] .. " syscall.master [config]")
end

local sysfile, outfile = arg[1], arg[2]
local metafn = arg[0]:gsub("/[^/]+$", "") .. "/syscall-meta.json"

config.merge(None)
config.mergeCompat()

local tbl = FreeBSDSyscall:new{sysfile = sysfile, config = config}
generate(tbl, outfile, metafn)
