#!/usr/libexec/flua
--
-- SPDX-License-Identifier: BSD-2-Clause
--
-- Copyright (c) 2026 Warner Losh <imp@bsdimp.com>
--

local ucl = require("ucl")
local parser = ucl.parser()
parser:parse_file(arg[1])
local data = parser:get_object()
local f <close> = assert(io.open(arg[2], "w"))

f:write("/* DO NOT EDIT-- this file is @" .. "generated by " .. arg[0] .. [[ */
]])

for _,v in ipairs(data) do
	if v.custom_impl then
		f:write(string.format(
		    "abi_long do_custom_%s(const os_syscall_args_t *);\n",
		    v.name))
	end
end
