#!/usr/libexec/flua
--
-- SPDX-License-Identifier: BSD-2-Clause
--
-- Copyright (c) 2026 Warner Losh <imp@FreeBSD.org>
-- Copyright (c) 2024 Tyler Baxter <agge@FreeBSD.org>
-- Copyright (c) 2019 Kyle Evans <kevans@FreeBSD.org>
--

-- Add library root to the package path.
local path = arg[0]:gsub("/[^/]+.lua$", "")
package.path = package.path .. ";" .. path .. "/?.lua;" .. os.getenv('FREEBSD_SYSCALL_DIR') .. "/?.lua"

local FreeBSDSyscall = require("core.freebsd-syscall")
local generator = require("tools.generator")
local config = require("config")
local qemu = require("qemu")

function generate(tbl, fn)
	local fout = assert(io.open(fn, "w+"))

	fout:write("/* DO NOT EDIT-- this file is @" .. "generated by " .. arg[0] .. [[ */

#define	PAD_(t)	(sizeof(abi_long) <= sizeof(t) ? \
		0 : sizeof(abi_long) - sizeof(t))

#if 0 /* TARGET_BIG_ENDIAN -- not needed since args in host byte order? */
#define	PADL_(t)	PAD_(t)
#define	PADR_(t)	0
#else
#define	PADL_(t)	0
#define	PADR_(t)	PAD_(t)
#endif
#define ARG(n,t)    char n##_l_[PADL_(t)]; t n; char n##_r_[PADR_(t)]

#define ARGS(x,sa)  \
	struct target_##x##_args *uap __unused = (struct target_##x##_args *)sa->args
]])
	-- Generate the system call implementation
	for _, v in pairs(tbl.syscalls) do
		if v:bsd_user_impl() then
			if not v.type.NOARGS and #v.args > 0 then
				fout:write("struct " .. v:struct_args() .. " { \n")
				for _, arg in ipairs(v.args) do
					t = qemu.target_type(arg.type)
					fout:write("    ARG(" .. arg.name .. "," .. t .. ");\n")
				end
				fout:write("};\n")
			else
				fout:write("struct " .. v:struct_args() .. " { } ;\n")
			end
		end
	end
end

if #arg < 1 or #arg > 2 then
	error("usage: " .. arg[0] .. " syscall.master")
end

local sysfile = arg[1]

config.merge(None)
config.mergeCompat()

-- The parsed system call table.
local tbl = FreeBSDSyscall:new{sysfile = sysfile, config = config}

file = arg[2] or "/dev/stdout"
generate(tbl, file)
